services:
  app:
    build: .
    container_name: gd-compressor
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gd-compressor.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.gd-compressor.entrypoints=websecure"
      - "traefik.http.routers.gd-compressor.tls=true"
      - "traefik.http.routers.gd-compressor.tls.certresolver=letsencrypt"
      - "traefik.http.services.gd-compressor.loadbalancer.server.port=5001"
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
