services:
  app:
    build: .
    container_name: gd-compressor
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gd-compressor.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.gd-compressor.entrypoints=websecure"
      - "traefik.http.routers.gd-compressor.tls=true"
      - "traefik.http.routers.gd-compressor.tls.certresolver=letsencrypt"
      - "traefik.http.services.gd-compressor.loadbalancer.server.port=5000"
      - "traefik.docker.network=traefik_network"

networks:
  traefik_network:
    external: true # must match the network Traefik is already running on
